import fs from 'fs'
import path from 'path'
import { defineConfig } from 'vite'

export default defineConfig(async ({ mode }) => {
  // Watch only on dev mode, ignoring auto-generated files
  const watch = mode === 'dev' && {
    exclude: ['lib/components/index.js']
  }

  return {
    build: {
      watch,
      lib: {
        entry: {
          components: path.resolve(__dirname, 'lib/components/index.js'),
          jsx: path.resolve(__dirname, 'lib/jsx/index.js'),
          state: path.resolve(__dirname, 'lib/state/index.js')
        },
        name: '@tooooools/ui'
      }
    },

    plugins: [
      {
        name: 'build-components-index',
        apply: 'build',
        buildStart: () => {
          console.log('\ngenerating components/index.js...\n')
          const dir = path.resolve(__dirname, 'lib/components')

          fs.writeFileSync(
            path.join(dir, 'index.js'),
            [
              '// Auto-generated by the build-components-index plugin',
              ...fs.readdirSync(dir).map(filename =>
                /.*.jsx/.test(filename) &&
                  `export { default as ${path.parse(filename).name} } from './${filename}'`
              ).filter(Boolean),
              ''
            ].join('\n'),
            'utf8'
          )
        }
      }
    ],

    css: {
      devSourcemap: true,
      preprocessorOptions: {
        scss: {
          additionalData: `
            @import 'lib/style/reset';
            @import 'lib/style/variables';
          `
        }
      }
    },

    esbuild: {
      jsxInject: "import h from '/lib/jsx/h'",
      jsxFactory: 'h'
    }
  }
})
